sonar.projectKey=Netflux-Backend
sonar.projectName=Netflux Backend
sonar.sourceEncoding=UTF-8

sonar.sources=src,server.js,migrations,seeds
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

sonar.exclusions=node_modules/**,coverage/**
